#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List


TARGET_REL = "data/derived/archive_bundle_gap_report.json"


def load_rows(path: Path) -> List[Dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(payload, dict):
        return list(payload.get("rows") or [])
    if isinstance(payload, list):
        return payload
    raise ValueError(f"Unsupported gap payload type in {path}")


def build_summary(rows: List[Dict[str, Any]]) -> Dict[str, int]:
    def has_flag(row: Dict[str, Any], flag: str) -> bool:
        return flag in (row.get("flags") or [])

    return {
        "rows": len(rows),
        "bundle_empty_archive_nonempty": sum(1 for row in rows if has_flag(row, "bundle_empty_archive_nonempty")),
        "bundle_below_archive_positive_tables": sum(1 for row in rows if has_flag(row, "bundle_below_archive_positive_tables")),
        "bundle_severely_partial_vs_archive": sum(1 for row in rows if has_flag(row, "bundle_severely_partial_vs_archive")),
        "with_any_flags": sum(1 for row in rows if row.get("flags")),
    }


def append_unique(items: List[str], value: str) -> List[str]:
    if value not in items:
        items.append(value)
    return items


def main() -> None:
    parser = argparse.ArgumentParser(description="Import archive-vs-bundle gap report into the app bundle.")
    parser.add_argument("--root", default=".", help="Root of lombardia_camera_app_v35")
    parser.add_argument("--source", required=True, help="Source JSON generated by compare_camera_coverage.py")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    source = Path(args.source).resolve()
    if not source.exists():
        raise SystemExit(f"Source gap report not found: {source}")

    rows = load_rows(source)
    target = root / TARGET_REL
    target.parent.mkdir(parents=True, exist_ok=True)
    target_payload = {
        "generated_by": "import_archive_gap_report.py",
        "source_file": str(source).replace("\\", "/"),
        "summary": build_summary(rows),
        "rows": rows,
    }
    target.write_text(json.dumps(target_payload, ensure_ascii=False, indent=2), encoding="utf-8")

    manifest_path = root / "data" / "derived" / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest.setdefault("files", {})["archiveBundleGapReport"] = TARGET_REL.replace("\\", "/")
    notes = list((manifest.setdefault("project", {})).get("notes") or [])
    append_unique(notes, "Archive-vs-bundle gap diagnostics are part of the bundle metadata so missing years and municipalities stay explicit.")
    manifest["project"]["notes"] = notes
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")

    data_products_path = root / "data" / "derived" / "data_products.json"
    if data_products_path.exists():
        data_products = json.loads(data_products_path.read_text(encoding="utf-8"))
        for product in data_products.get("products") or []:
            if product.get("product_key") == "metadata_layer":
                extras = list(product.get("extra_dataset_keys") or [])
                product["extra_dataset_keys"] = append_unique(extras, "archiveBundleGapReport")
        data_products_path.write_text(json.dumps(data_products, ensure_ascii=False, indent=2), encoding="utf-8")

    provenance_path = root / "data" / "derived" / "provenance.json"
    if provenance_path.exists():
        provenance = json.loads(provenance_path.read_text(encoding="utf-8"))
        entries = provenance.get("entries") or []
        if not any(entry.get("dataset_key") == "archiveBundleGapReport" for entry in entries):
            entries.append({
                "dataset_key": "archiveBundleGapReport",
                "path": TARGET_REL.replace("\\", "/"),
                "produced_by": "compare_camera_coverage.py + import_archive_gap_report.py",
                "source_class": "coverage_diagnostics",
                "transformation_steps": [
                    "compare the canonical Lombardia archive against the currently published app bundle",
                    "carry the gap report into the static bundle as declared metadata"
                ],
                "limitations": [
                    "the report diagnoses missing or partial coverage but does not repair the missing rows",
                    "historical grouped years can have archive navigation without positive tables, so flags need interpretation year by year"
                ]
            })
        provenance["entries"] = entries
        provenance_path.write_text(json.dumps(provenance, ensure_ascii=False, indent=2), encoding="utf-8")

    print(json.dumps({
        "root": str(root),
        "target": str(target),
        "rows": len(rows),
        "summary": target_payload["summary"],
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
