#!/usr/bin/env python3
"""Re-apply the canonical party taxonomy to derived CSVs in place.

What it does
============

Streams ``data/derived/municipality_results_long.csv`` row by row, looks
up each ``party_raw`` against the curated ``PARTY_FALLBACKS`` list in
``scripts/preprocess.py`` (which mirrors ``modules/shared.js``), and
rewrites the ``party_family`` and ``bloc`` columns with the canonical
values.  All other columns are passed through untouched.

Why this exists
===============

The CSV used to be generated by an earlier preprocessor whose taxonomy
covered only ~11 parties.  Anything outside that list (L'Ulivo, AN, UDC,
RC, IdV, Pensionati, Verdi pre-AVS, ...) was stamped with
``bloc=altro`` / ``party_family=altro`` and downstream bloc-aware
aggregations got polluted with "altro 54%" style noise.  The web app
already re-applies the JS taxonomy at runtime to mask the problem, but
downstream consumers that read the CSV directly (BI tools, audits,
exports) still see the broken values.  Running this script bakes the
correct ``bloc`` / ``party_family`` into the CSV so the two layers
agree.

Usage
=====

::

    python3 scripts/sync_taxonomy_in_place.py
    python3 scripts/sync_taxonomy_in_place.py --dry-run
    python3 scripts/sync_taxonomy_in_place.py --csv path/to/results_long.csv

Idempotent: re-running on an already-synced CSV is a no-op.

Safety
======

- Writes to a temp file in the same directory then atomically replaces
  the original on success.
- Refuses to run if the required columns ``party_raw``, ``party_family``
  and ``bloc`` are missing.
- Never touches ``party_raw`` / ``party_std`` / ``votes`` / vote_share``
  / any other column.  Only ``party_family`` and ``bloc`` are rewritten.

This script does NOT regenerate ``municipality_summary.csv``.  The web
app re-derives ``dominant_block`` at runtime from the (now correct)
long rows, so the summary CSV's stale value is not user-visible.  A
follow-up could update it for parity with downstream CSV consumers.
"""
from __future__ import annotations

import argparse
import csv
import os
import sys
import tempfile
from pathlib import Path
from typing import Dict

# Make scripts/ importable so we can reuse the canonical taxonomy.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from preprocess import infer_party_meta  # noqa: E402

REQUIRED_COLUMNS = {"party_raw", "party_family", "bloc"}


def sync_results_long(csv_path: Path, dry_run: bool = False) -> Dict[str, int]:
    """Stream-rewrite ``csv_path``, updating bloc / party_family.

    Returns a stats dict with ``total``, ``bloc_changed`` and
    ``family_changed`` counters.  When ``dry_run`` is set the original
    file is left untouched and the temp file is removed.
    """
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV not found: {csv_path}")

    stats = {"total": 0, "bloc_changed": 0, "family_changed": 0, "no_match": 0}
    cache: Dict[str, Dict[str, str]] = {}

    tmp = tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        newline="",
        delete=False,
        dir=str(csv_path.parent),
        prefix=csv_path.name + ".",
        suffix=".tmp",
    )
    tmp_path = Path(tmp.name)
    try:
        with csv_path.open("r", encoding="utf-8", newline="") as src:
            reader = csv.DictReader(src)
            fieldnames = reader.fieldnames or []
            missing = REQUIRED_COLUMNS - set(fieldnames)
            if missing:
                raise ValueError(
                    f"CSV is missing required columns: {sorted(missing)}"
                )
            writer = csv.DictWriter(tmp, fieldnames=fieldnames, lineterminator="\n")
            writer.writeheader()
            for row in reader:
                stats["total"] += 1
                party_raw = (row.get("party_raw") or "").strip()
                meta = cache.get(party_raw)
                if meta is None:
                    meta = infer_party_meta(party_raw)
                    cache[party_raw] = meta
                if meta.get("family") == "altro" and meta.get("bloc") == "altro":
                    stats["no_match"] += 1
                new_family = meta.get("family") or row.get("party_family") or "altro"
                new_bloc = meta.get("bloc") or row.get("bloc") or "altro"
                if row.get("party_family") != new_family:
                    stats["family_changed"] += 1
                    row["party_family"] = new_family
                if row.get("bloc") != new_bloc:
                    stats["bloc_changed"] += 1
                    row["bloc"] = new_bloc
                writer.writerow(row)
        tmp.close()
        if dry_run:
            tmp_path.unlink(missing_ok=True)
        else:
            os.replace(str(tmp_path), str(csv_path))
    except BaseException:
        tmp.close()
        tmp_path.unlink(missing_ok=True)
        raise
    return stats


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--csv",
        type=Path,
        default=Path("data/derived/municipality_results_long.csv"),
        help="Path to the long-format results CSV (default: %(default)s).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Read everything but do not overwrite the CSV.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    stats = sync_results_long(args.csv, dry_run=args.dry_run)
    print(f"Rows processed:      {stats['total']:>10}")
    print(f"bloc rewritten:      {stats['bloc_changed']:>10}")
    print(f"family rewritten:    {stats['family_changed']:>10}")
    print(f"unmatched party_raw: {stats['no_match']:>10}")
    if args.dry_run:
        print("(dry-run: CSV not modified)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
